spring.application.name=api-clientes

# Porta do servidor web
server.port=8081

# Acesso ao banco de dados
datasource.host=jdbc:postgresql://localhost:5432/bd-api-clientes
datasource.username=postgres
datasource.password=coti

# permissoes de cors
cors.enabled=http://localhost:4200

