CREATE TABLE CLIENTES(
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE

);

CREATE TABLE ENDERECOS(
    ID SERIAL PRIMARY KEY,
    LOGRADOURO VARCHAR(255) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR(255),
    BAIRRO VARCHAR(255) NOT NULL,
    CIDADE VARCHAR(255) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    CEP VARCHAR(10) NOT NULL,
    CLIENTE_ID INT NOT NULL,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID)
);